name: QA control

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '17 5 * * 1'

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  qa:
    uses: codenautas/.github/.github/workflows/qa-control.yaml@b01220c20887c52ba71379ae6d2f24c22ee9aa9e # main
